# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install Yarn
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install
      
    - name: Lint
      run: yarn lint
      
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install Yarn
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install
      
    - name: Create env file
      run: cp .env.example .env
        
    - name: Run tests
      run: yarn test
